Repository Team-Recordy/Recordy-Android, pull requests merged in 2024-10, with the labels that each got.

#128 Feature/#127 mypage modify
  core/designsystem/src/main/java/com/record/designsystem/theme/Color.kt
  feature/mypage/src/main/java/com/record/mypage/MypageContract.kt
  feature/mypage/src/main/java/com/record/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/record/mypage/MypageTab.kt
  feature/mypage/src/main/java/com/record/mypage/MypageViewModel.kt
  feature/mypage/src/main/java/com/record/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/record/mypage/screen/BookmarkScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/EmptyDataScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/RecordScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/TasteScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
Labels: 기능구현 Skrr, 나경 🪼🐹

#133 Feature/#131 login onboarding UI
  core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
  core/designsystem/src/main/res/drawable/img_viskit_logo.png
  feature/login/src/main/java/com/record/login/LoginScreen.kt
  feature/login/src/main/java/com/record/login/navigation/LoginNavigation.kt
  feature/login/src/main/java/com/record/login/singup/SignUpScreen.kt
  feature/login/src/main/java/com/record/login/singup/SignUpState.kt
  feature/login/src/main/java/com/record/login/singup/SignUpViewModel.kt
  feature/login/src/main/java/com/record/login/singup/screen/NamingScreen.kt
  feature/login/src/main/java/com/record/login/singup/screen/PolicyScreen.kt
  feature/login/src/main/java/com/record/login/singup/screen/SignUpSuccessScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
Labels: 쌈뽕한 UI, 명석 💡✨

#132 Feature/#129 place detail UI
  core/designsystem/src/main/java/com/record/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_more_informations.xml
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/record/detail/DetailScreen.kt
  feature/detail/src/main/java/com/record/detail/DetailpageContract.kt
  feature/detail/src/main/java/com/record/detail/DetailpageTab.kt
  feature/detail/src/main/java/com/record/detail/DetailpageViewModel.kt
  feature/detail/src/main/java/com/record/detail/navigation/DetailNavigation.kt
  feature/detail/src/main/java/com/record/detail/screen/ChipTab.kt
  feature/detail/src/main/java/com/record/detail/screen/EmptyDataScreen.kt
  feature/detail/src/main/java/com/record/detail/screen/ListScreen.kt
  feature/detail/src/main/java/com/record/detail/screen/ReviewScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
Labels: 기능구현 Skrr, 쌈뽕한 UI, 나경 🪼🐹

#137 Feature/#134 profile edit
  core/designsystem/src/main/res/drawable/ic_camera.xml
  core/designsystem/src/main/res/drawable/img_profileedit.png
  data/user/build.gradle.kts
  data/user/src/main/java/com/record/user/model/remote/request/RequestUpdateProfileDto.kt
  data/user/src/main/java/com/record/user/model/remote/response/ResponseGetUserProfileDto.kt
  data/user/src/main/java/com/record/user/repository/UserRepositoryImpl.kt
  data/user/src/main/java/com/record/user/source/remote/RemoteUserDataSource.kt
  data/video/src/main/java/com/record/video/source/remote/RemoteUploadDataSource.kt
  domain/user/src/main/java/com/record/user/repository/UserRepository.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/record/setting/SettingContract.kt
  feature/setting/src/main/java/com/record/setting/SettingScreen.kt
  feature/setting/src/main/java/com/record/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/record/setting/navigate/SettingNavigation.kt
  feature/setting/src/main/java/com/record/setting/profileedit/ProfileEditRoute.kt
  feature/setting/src/main/java/com/record/setting/profileedit/ProfileEditState.kt
  feature/setting/src/main/java/com/record/setting/profileedit/ProfileEditViewModel.kt
  remote/user/src/main/java/com/record/user/api/UserApi.kt
  remote/user/src/main/java/com/record/user/datasource/RemoteUserDataSourceImpl.kt
  remote/video/src/main/java/com/record/video/datasource/RemoteUploadDataSourceImpl.kt
Labels: 쌈뽕한 UI, 명석 💡✨
