Repository Team-Recordy/Recordy-Android, pull requests merged in 2024-07, with the labels that each got.

#5 Feature/#3 add component package
  core/designsystem/src/main/java/com/record/designsystem/component/button/dummy.kt
  core/designsystem/src/main/java/com/record/designsystem/component/progressbar/dummy.kt
Labels: 기초세팅팅팅탱탱탱후라이팬놀이, 상욱 🤴🏻👑

#43 [chore] #42 configuration options
  renovate.json
Labels: 상욱 🤴🏻👑, renovate

#45 Feature/#6 component progressbar button
  core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
  core/designsystem/src/main/java/com/record/designsystem/component/button/dummy.kt
  core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
  core/designsystem/src/main/java/com/record/designsystem/component/progressbar/dummy.kt
Labels: 쌈뽕한 UI, 서희 🐶🪽

#46 Feature/#7 component textfield
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
  core/model/src/main/java/com/record/model/ValidateResult.kt
Labels: 쌈뽕한 UI, 나경 🪼🐹

#73 Docs/#50 readme.md update
  README.md
Labels: 문서작업 yo yo, 나경 🪼🐹

#79 Feature/#53 mypage view frame
  core/designsystem/src/main/res/drawable/img_bg_bubble.png
  core/designsystem/src/main/res/drawable/img_bookmark.png
  core/designsystem/src/main/res/drawable/img_camera.png
  core/designsystem/src/main/res/drawable/img_question.png
  feature/mypage/src/main/java/com/record/mypage/MypageContract.kt
  feature/mypage/src/main/java/com/record/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/record/mypage/MypageTab.kt
  feature/mypage/src/main/java/com/record/mypage/MypageViewModel.kt
  feature/mypage/src/main/java/com/record/mypage/screen/BookmarkScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/EmptyDataScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/RecordScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/SampleData.kt
  feature/mypage/src/main/java/com/record/mypage/screen/TasteScreen.kt
  feature/mypage/src/main/res/drawable/ic_setting_24.xml
  feature/mypage/src/main/res/drawable/img_for_empty.png
Labels: 기능구현 Skrr, 쌈뽕한 UI, 나경 🪼🐹

#84 [feat] #83 add bookmark icon to record/ bookmark screen
  feature/mypage/src/main/java/com/record/mypage/screen/BookmarkScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/RecordScreen.kt
Labels: 쌈뽕한 UI, 나경 🪼🐹

#86 Feature/#70 auth api
  app/build.gradle.kts
  core/buildconfig/src/main/java/com/record/buildconfig/impl/BuildConfigFieldsProviderImpl.kt
  core/datastore/src/main/java/com/record/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/record/datastore/token/AuthToken.kt
  core/datastore/src/main/java/com/record/datastore/token/TokenDataSerializer.kt
  core/datastore/src/main/java/com/record/datastore/token/TokenDataStore.kt
  core/model/src/main/java/com/record/model/AuthEntity.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/record/network/AuthenticationIntercept.kt
  core/network/src/main/java/com/record/network/TokenRefreshService.kt
  core/network/src/main/java/com/record/network/authenticator/RecordyAuthenticator.kt
  core/network/src/main/java/com/record/network/di/NetworkModule.kt
  core/network/src/main/java/com/record/network/model/ResponsePostAuthRefreshDto.kt
  data/auth/src/main/kotlin/com/record/auth/di/AuthModule.kt
  data/auth/src/main/kotlin/com/record/auth/model/request/RequestSignInDto.kt
  data/auth/src/main/kotlin/com/record/auth/model/request/RequestSignUpDto.kt
  data/auth/src/main/kotlin/com/record/auth/model/response/ResponseGetAccessTokenDto.kt
  data/auth/src/main/kotlin/com/record/auth/model/response/ResponseSignInDto.kt
  data/auth/src/main/kotlin/com/record/auth/repository/AuthRepositoryImpl.kt
  data/auth/src/main/kotlin/com/record/auth/source/local/AuthLocalDataSource.kt
  data/auth/src/main/kotlin/com/record/auth/source/remote/AuthRemoteDataSource.kt
  data/recordy/build.gradle.kts
  domain/auth/src/main/java/com/recordy/auth/model/AuthAgreementEntity.kt
  domain/auth/src/main/java/com/recordy/auth/model/AuthEntity.kt
  domain/auth/src/main/java/com/recordy/auth/repository/AuthRepository.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/record/login/LoginScreen.kt
  feature/login/src/main/java/com/record/login/LoginState.kt
  feature/login/src/main/java/com/record/login/LoginViewModel.kt
  feature/login/src/main/java/com/record/login/navigation/LoginNavigation.kt
  feature/login/src/main/java/com/record/login/singup/SignUpScreen.kt
  feature/login/src/main/java/com/record/login/singup/SignUpState.kt
  feature/login/src/main/java/com/record/login/singup/SignUpViewModel.kt
  feature/login/src/main/java/com/record/login/singup/screen/NamingScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  local/auth/build.gradle.kts
  local/auth/src/main/java/com/recordy/auth/datasource/AuthLocalDataSourceImpl.kt
  local/auth/src/main/java/com/recordy/auth/di/AuthLocalDataModule.kt
  remote/auth/build.gradle.kts
  remote/auth/src/main/java/com/recordy/auth/api/AuthService.kt
  remote/auth/src/main/java/com/recordy/auth/datasource/AuthRemoteDataSourceImpl.kt
  remote/auth/src/main/java/com/recordy/auth/di/ApiModule.kt
  remote/auth/src/main/java/com/recordy/auth/di/DataModule.kt
  settings.gradle.kts
Labels: 기능구현 Skrr, 명석 💡✨

#89 Feature/#87 setting
  data/auth/src/main/kotlin/com/record/auth/repository/AuthRepositoryImpl.kt
  data/auth/src/main/kotlin/com/record/auth/source/remote/AuthRemoteDataSource.kt
  domain/auth/src/main/java/com/recordy/auth/repository/AuthRepository.kt
  feature/mypage/src/main/java/com/record/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/record/mypage/navigation/MypageNavigation.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/record/setting/SettingContract.kt
  feature/setting/src/main/java/com/record/setting/SettingDialog.kt
  feature/setting/src/main/java/com/record/setting/SettingScreen.kt
  feature/setting/src/main/java/com/record/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/record/setting/navigate/SettingNavigation.kt
  remote/auth/src/main/java/com/recordy/auth/api/AuthService.kt
  remote/auth/src/main/java/com/recordy/auth/datasource/AuthRemoteDataSourceImpl.kt
  settings.gradle.kts
Labels: 기능구현 Skrr, 쌈뽕한 UI, 명석 💡✨

#99 Feature/#96 login
  app/build.gradle.kts
  core/datastore/src/main/java/com/record/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/record/datastore/token/TokenDataStore.kt
  core/datastore/src/main/java/com/record/datastore/user/UserData.kt
  core/datastore/src/main/java/com/record/datastore/user/UserDataSerializer.kt
  core/datastore/src/main/java/com/record/datastore/user/UserDataStore.kt
  core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
  core/model/src/main/java/com/record/model/AuthEntity.kt
  core/network/src/main/java/com/record/network/AuthenticationIntercept.kt
  data/auth/src/main/kotlin/com/record/auth/model/response/ResponseSignInDto.kt
  data/auth/src/main/kotlin/com/record/auth/repository/AuthRepositoryImpl.kt
  data/auth/src/main/kotlin/com/record/auth/source/remote/AuthRemoteDataSource.kt
  data/user/build.gradle.kts
  data/user/src/main/java/com/record/user/repository/UserRepositoryImpl.kt
  data/user/src/main/java/com/record/user/source/local/UserLocalDataSource.kt
  domain/auth/src/main/java/com/recordy/auth/repository/AuthRepository.kt
  domain/user/src/main/java/com/record/user/repository/UserRepository.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/record/login/LoginScreen.kt
  feature/login/src/main/java/com/record/login/LoginState.kt
  feature/login/src/main/java/com/record/login/LoginViewModel.kt
  feature/login/src/main/java/com/record/login/singup/SignUpScreen.kt
  feature/login/src/main/java/com/record/login/singup/SignUpState.kt
  feature/login/src/main/java/com/record/login/singup/SignUpViewModel.kt
  local/user/build.gradle.kts
  local/user/src/main/java/com/record/user/datasource/UserLocalDataSourceImpl.kt
  local/user/src/main/java/com/record/user/di/UserLocalDataModule.kt
  remote/auth/src/main/java/com/recordy/auth/api/AuthService.kt
  remote/auth/src/main/java/com/recordy/auth/datasource/AuthRemoteDataSourceImpl.kt
  settings.gradle.kts
Labels: 기능구현 Skrr, 쌈뽕한 UI, 서버커넥팅팅팅탱탱탱후라이팬놀이, 명석 💡✨

#100 Feature/#94 mypage route connect
  feature/mypage/src/main/java/com/record/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/record/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/record/mypage/screen/BookmarkScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/RecordScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  feature/video/src/main/java/com/record/video/navigation/VideoNavigation.kt
Labels: 기능구현 Skrr, 나경 🪼🐹

#104 [refactor] #103 setting , login
  feature/login/src/main/java/com/record/login/singup/SignUpScreen.kt
  feature/login/src/main/java/com/record/login/singup/SignUpViewModel.kt
  feature/login/src/main/java/com/record/login/singup/screen/NamingScreen.kt
  feature/login/src/main/java/com/record/login/singup/screen/PolicyScreen.kt
  feature/setting/src/main/java/com/record/setting/SettingScreen.kt
  feature/setting/src/main/java/com/record/setting/SettingViewModel.kt
Labels: 기능구현 Skrr, 명석 💡✨

#106 Feature/#81 follow api
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/record/designsystem/component/container/UserDataContainer.kt
  core/model/src/main/java/com/record/model/UserData.kt
  data/user/src/main/java/com/record/user/repository/UserRepositoryImpl.kt
  feature/mypage/src/main/java/com/record/mypage/follow/FollowScreen.kt
  feature/mypage/src/main/java/com/record/mypage/follow/FollowState.kt
  feature/mypage/src/main/java/com/record/mypage/follow/FollowViewModel.kt
  feature/mypage/src/main/java/com/record/mypage/follow/FollowerScreen.kt
  feature/mypage/src/main/java/com/record/mypage/follow/FollowingScreen.kt
  feature/mypage/src/main/java/com/record/mypage/navigation/MypageNavigation.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  feature/profile/src/main/java/com/record/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/record/profile/ProfileState.kt
  feature/profile/src/main/java/com/record/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/record/profile/navigation/ProfileNavigation.kt
Labels: 기능구현 Skrr, 서버커넥팅팅팅탱탱탱후라이팬놀이, 서희 🐶🪽

#107 Feature/#102 video detail api
  app/src/main/AndroidManifest.xml
  core/cache/build.gradle.kts
  core/cache/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/record/designsystem/component/badge/RecordyLocationBadge.kt
  core/model/src/main/java/com/record/model/Cursor.kt
  core/ui/src/main/java/com/record/ui/scroll/OnBottomReached.kt
  data/video/src/main/java/com/record/video/model/remote/response/ResponseGetSliceVideoDto.kt
  data/video/src/main/java/com/record/video/repository/VideoRepositoryImpl.kt
  data/video/src/main/java/com/record/video/source/local/LocalUserInfoDataSource.kt
  data/video/src/main/java/com/record/video/source/remote/RemoteVideoDataSource.kt
  domain/video/src/main/java/com/record/video/repository/VideoRepository.kt
  feature/home/src/main/java/com/record/home/HomeContract.kt
  feature/home/src/main/java/com/record/home/HomeScreen.kt
  feature/home/src/main/java/com/record/home/HomeViewModel.kt
  feature/mypage/src/main/java/com/record/mypage/MypageContract.kt
  feature/mypage/src/main/java/com/record/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/record/mypage/MypageViewModel.kt
  feature/mypage/src/main/java/com/record/mypage/screen/BookmarkScreen.kt
  feature/mypage/src/main/java/com/record/mypage/screen/RecordScreen.kt
  feature/navigator/src/main/java/com/record/navigator/InMainNavTab.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/record/navigator/MainScreen.kt
  feature/profile/src/main/java/com/record/profile/ProfileContract.kt
  feature/profile/src/main/java/com/record/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/record/profile/ProfileState.kt
  feature/profile/src/main/java/com/record/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/record/profile/navigation/ProfileNavigation.kt
  feature/video/src/main/java/com/record/video/VideoContract.kt
  feature/video/src/main/java/com/record/video/VideoScreen.kt
  feature/video/src/main/java/com/record/video/VideoViewModel.kt
  feature/video/src/main/java/com/record/video/navigation/VideoNavigation.kt
  feature/video/src/main/java/com/record/video/videodetail/VideoDetailContract.kt
  feature/video/src/main/java/com/record/video/videodetail/VideoDetailScreen.kt
  feature/video/src/main/java/com/record/video/videodetail/VideoDetailViewModel.kt
  local/user/build.gradle.kts
  local/user/src/main/java/com/record/user/datasource/UserLocalDataSourceImpl.kt
  local/user/src/main/java/com/record/user/di/UserLocalDataModule.kt
  project.dot.png
  remote/video/src/main/java/com/record/video/api/VideoApi.kt
  remote/video/src/main/java/com/record/video/datasource/RemoteVideoDataSourceImpl.kt
  settings.gradle.kts
Labels: 서버커넥팅팅팅탱탱탱후라이팬놀이, 상욱 🤴🏻👑

#109 Refactor/#103 setting & login
  feature/login/src/main/java/com/record/login/singup/SignUpScreen.kt
  feature/login/src/main/java/com/record/login/singup/SignUpState.kt
  feature/login/src/main/java/com/record/login/singup/SignUpViewModel.kt
  feature/login/src/main/java/com/record/login/singup/screen/NamingScreen.kt
  feature/navigator/src/main/java/com/record/navigator/MainNavigator.kt
  feature/setting/src/main/java/com/record/setting/SettingContract.kt
  feature/setting/src/main/java/com/record/setting/SettingDialog.kt
  feature/setting/src/main/java/com/record/setting/SettingScreen.kt
  feature/setting/src/main/java/com/record/setting/SettingViewModel.kt
Labels: 기능구현 Skrr, 명석 💡✨

#114 Docs/#50 readme.md update
  README.md
Labels: 문서작업 yo yo, 나경 🪼🐹
